### ISSUE TITLE
refactoring: get a proper bootstrapable setup?

### ISSUE THREAD

**Issue by hanetzer** [haubi/newlib-cygwin#1]
Greetings. I'm fairly close to having an un-prefixed gentoo/cygwin setup (cygentoo, perhaps),
and the major thing that will prevent this from working is dev-libs/cygwin is hella old, and the
build scripts for newlib-cygwin are pretty bad as far as libc and libc-likes go.

If the code was refactored (mostly build scripts, actually) to be bootstrappable in the same way
as glibc, musl, and mingw64-runtime are, the process would be finishable.

Opening an issue here since you're rarely on #gentoo-prefix when I am, it seems.

**Comment by haubi** [comment]
Well... although something like "Gentoo GNU/Cygwin" is an awesome goal by itself, it is beyond my head, as I do need "Gentoo GNU/Prefix" to work on AIX+Linux+Windows, and my involvement with newlib-cygwin is to fix for running Gentoo Portage - specifically the fork() was incomplete.

That being said: For any un-prefixed "Gentoo GNU/whatever" setup I believe there is need for some binary stage3 tarball anyway (like http://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64/), and for compiling dev-libs/cygwin it should not be a problem to depend on additional packages, much like necessary for current upstream cygwin.cygport right now.

Agreed, dev-libs/cygwin is horribly old, and as far as I can tell, it's current intention is for use with crossdev. To update without breaking it's crossdev usage please tell to toolchain@gentoo.org as the current maintainers of dev-libs/cygwin ebuilds.

And for patches against newlib-cygwin, anything upstream acceptable is preferred (as with any other package) - the forkables branch is promised to be integrated upstream with release 3.0.

One more thing: Although the forkables feature should keep fork() working across replaced dlls (including cygwin1.dll), updating cygwin1.dll itself currently breaks the exec() system call because of "multiple versions of cygwin1.dll being found", as the version of cygwin's shared memory is tightly bound to the version of cygwin1.dll.

In fact, cygwin1.dll is a hybrid dll containing a libc (newlib) and a "kernel" (cygwin), but I doubt splitting up into sys-libs/newlib and sys-kernel/cygwin is a good idea without upstream acceptance&support.
(Remember: updating sys-kernel/* does require a machine reboot on Linux.)
Instead, probably it's easier to create some internal interface to access any version of cygwin's shared memory.

My 2 cents,
/haubi/
